services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: app
      POSTGRES_DB: app
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      retries: 15
    networks:
      - backend_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend_network
    depends_on:
      - db

  backend:
    image: deltronfr/monitoring-backend-repo:b5486c5d209d9abb81bbef7b8202bfe2f2ffbcea
    container_name: backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - backend_network
      - frontend_network

  frontend:
    image: deltronfr/monitoring-frontend-repo:b5486c5d209d9abb81bbef7b8202bfe2f2ffbcea
    container_name: frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - db
      - backend
    networks:
      - frontend_network
      - backend_network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - adminer
      - certbot
    networks:
      - monitoring_network
      - frontend_network
      - backend_network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: ["/bin/sh", "-c", "certbot renew --standalone --quiet && sleep 12h & wait"]
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

    networks:
      - monitoring_network
      - frontend_network
      - backend_network

volumes:
  postgres_vol:
  data:
  letsencrypt:

networks:
  frontend_network:
    external: true
  backend_network:
    external: true
  monitoring_network:
    external: true
