services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.external-url=/prometheus'
    networks:
      - frontend_network
      - backend_network
      - monitoring_network
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - prometheus
    networks:
      - frontend_network
      - backend_network
      - monitoring_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend_network
      - frontend_network
      - monitoring_network
    depends_on:
      - backend
      - frontend
      - adminer
      - db
    privileged: true
    
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    user: "root"
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/data/loki
    command: --config.file=/etc/loki/loki-config.yaml
    networks:
      - backend_network
      - monitoring_network
      - frontend_network
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log                  
      - ./monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped
    command: --config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - backend_network
      - frontend_network
      - monitoring_network

volumes:
  prom_data:
  grafana-data:
  loki-data:

