resource_name       = "resource"
location            = "West Europe"
address_space       = ["10.0.0.0/16"]
address_prefixes    = ["10.0.0.0/24"]
vm_size             = "Standard_B2s"
admin_username      = "azureuser"
ssh_key_path        = "~.ssh/id_rsa.pub"
inventory_file_path = "~/ansible/inventory.ini"
ssh_pri_key         = "~/.ssh/id_rsa"
dns_password        = "TryHackMe"
