env_vars:
  DOMAIN: "<your_domain_name>"
  ENVIRONMENT: "production"
  PROJECT_NAME: "Full Stack FastAPI Project"
  STACK_NAME: "full-stack-fastapi-project"
  BACKEND_CORS_ORIGINS: "http://<your_domain_name>,http://<your_domain_name>:5173,https://<your_domain_name>,https://<your_domain_name>:5173"
  SECRET_KEY: "changethis123"
  FIRST_SUPERUSER: "changethis12320gmail.com"
  FIRST_SUPERUSER_PASSWORD: "devopsdoj3"
  USERS_OPEN_REGISTRATION: "True"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  EMAILS_FROM_EMAIL: "info@example.com"
  SMTP_TLS: "True"
  SMTP_SSL: "False"
  SMTP_PORT: "587"
  POSTGRES_SERVER: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app_db"
  POSTGRES_USER: "app"
  POSTGRES_PASSWORD: "password"
  EMAIL: "<your_actual_email>"