name: Workflow for setting up monitoring with ansible

on:
  workflow_run:
    workflows: ["Deploy infrastructure"]
    types: [completed]


jobs:
  deploy:
    name: deploy monitoring stack
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible playbook
        run: |
          cd infrastructure/ansible
          ansible-playbook playbook.yaml