name: Deploy application stack

on:
  push:
    branches: deployment

jobs:
  deploy:
    name: Deploy to provisioned infrastructure
    runs-on: ubuntu-latest

    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4


      - name: deploy to vm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: deltronfr.mooo.com
          username: ${{ secrets.TF_VARS_ADMIN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
              
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
                if [ ! -d "full-stack_gitops/.git" ]; then
                  git clone --branch deployment git@github.com:deltron-fr/full-stack_gitops.git full-stack_gitops
                fi

                cd full-stack_gitops
                git pull origin deployment

                cd application/
                echo "${{ secrets.DOCKER_ENV_FILE }}" > .env
                sudo docker compose -f compose.app.yaml down --volumes || true
                docker compose -f compose.app.yaml up -d --force-recreate
